version: '3.8'

services:
  cordra:
    container_name: cordra
    restart: always
    image: public.ecr.aws/dissco/cordra:latest
    env_file:
      - ./cordra/variables.env
    volumes:
      - ./data:/opt/cordra/data
    ports:
      - "2641:2641"
  tettris_marketplace:
    container_name: tettris_marketplace
    restart: always
    image: public.ecr.aws/dissco/tettris-marketplace:sha-affacca
  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx:1.26
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx:ro
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/letsencrypt/:rw
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./certbot/conf/:/etc/letsencrypt/:rw
      - ./certbot/www/:/var/www/certbot/:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
